{
  "sender_id": "0020ec64-fe66-48c2-b64c-de592619e345:d077fdc1-ee90-4cf6-a796-535cd514084e:aa2da037-dc5d-4598-907c-207715346cbd",
  "send_metrics": true,
  "send_errors": true,
  "disable_logging": false
}